-- AlterTable
ALTER TABLE "Meal" ADD COLUMN "isAcidic" BOOLEAN;
ALTER TABLE "Meal" ADD COLUMN "isCreamy" BOOLEAN;
ALTER TABLE "Meal" ADD COLUMN "isHighCarb" BOOLEAN;
ALTER TABLE "Meal" ADD COLUMN "isHighVeg" BOOLEAN;
ALTER TABLE "Meal" ADD COLUMN "makesLunch" BOOLEAN;
ALTER TABLE "Meal" ADD COLUMN "outdoorCooking" BOOLEAN;
