services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: backend
    volumes:
      - type: volume
        target: /app/static
        source: static_files
    ports:
      - 3200

  nginx:
    image: nginx:1.25.5-alpine-slim
    depends_on:
      - app
    volumes:
      - static_files:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

volumes:
  static_files:
