/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BFormTags: typeof import('bootstrap-vue-next')['BFormTags']
    CurrentWeekSummary: typeof import('./src/components/home/CurrentWeekSummary.vue')['default']
    EditPlanCard: typeof import('./src/components/editplans/EditPlanCard.vue')['default']
    EditPlanForm: typeof import('./src/components/editplans/EditPlanForm.vue')['default']
    EditPlanTable: typeof import('./src/components/editplans/EditPlanTable.vue')['default']
    HomeTable: typeof import('./src/components/home/HomeTable.vue')['default']
    IngredientList: typeof import('./src/components/archived/IngredientList.vue')['default']
    IngredientsList: typeof import('./src/components/meals/IngredientsList.vue')['default']
    LoadingWheel: typeof import('./src/components/LoadingWheel.vue')['default']
    LunchDaysTable: typeof import('./src/components/LunchDaysTable.vue')['default']
    LunchTab: typeof import('./src/components/archived/LunchTab.vue')['default']
    MealCard: typeof import('./src/components/MealCard.vue')['default']
    MealForm: typeof import('./src/components/archived/MealForm.vue')['default']
    MealFormEdit: typeof import('./src/components/archived/MealFormEdit.vue')['default']
    MealList: typeof import('./src/components/archived/MealList.vue')['default']
    MealPlanForm: typeof import('./src/components/archived/MealPlanForm.vue')['default']
    MealsList: typeof import('./src/components/meals/MealsList.vue')['default']
    MealTab: typeof import('./src/components/archived/MealTab.vue')['default']
    MealTable: typeof import('./src/components/archived/MealTable.vue')['default']
    ModalComp: typeof import('./src/components/archived/ModalComp.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewMealBtn: typeof import('./src/components/archived/NewMealBtn.vue')['default']
    NewMealModal: typeof import('./src/components/archived/NewMealModal.vue')['default']
    NewMealPlanBtn: typeof import('./src/components/archived/NewMealPlanBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    SuggestionDisplay: typeof import('./src/components/SuggestionDisplay.vue')['default']
    SummaryCard: typeof import('./src/components/home/SummaryCard.vue')['default']
    TagInputTest: typeof import('./src/components/archived/TagInputTest.vue')['default']
    TodayCard: typeof import('./src/components/home/TodayCard.vue')['default']
  }
}
